// app/lib/landing.jsx
import { useLocation } from "preact-iso";

export default function Landing() {
  const { route } = useLocation();

  async function onclick() {
    const res = await fetch("/api/sessions/create", {
      method: "POST",
    });
    if (res.status !== 200) {
      alert("Failed to create new session. Please refresh and try again.");
    }
    const { uuid } = await res.json();
    route("/session/" + uuid);
  }

  return (
    <div>
      <button onClick={onclick}>Create New Voting Session</button>
    </div>
  );
}

// app/lib/Landing.svelte
<script lang="ts">
  import { navigate } from "svelte-tiny-router";

  async function onclick() {
    const res = await fetch("/api/sessions/create", {
      method: "POST",
    });
    if (res.status !== 200) {
      alert("Failed to create new session. Please refresh and try again.");
    }
    const { uuid } = await res.json();
    navigate("/session/" + uuid);
  }
</script>

<div>
  <button {onclick}>Create New Voting Session</button>
</div>
