// app/App.svelte
<script lang="ts">
  import Landing from "./lib/Landing.svelte";
  import Poker from "./lib/Poker.svelte";

  import { Router, Route } from "svelte-tiny-router";

  export let url = "";
</script>

<Router {url}>
  <main>
    <Route path="/" component={Landing} />
    <Route path="/session/:id" component={Poker} />
  </main>
</Router>

<style>
</style>

// app/app.jsx
import { LocationProvider, Router, Route } from "preact-iso";
import "./app.css";
import Landing from "./lib/landing";
import Poker from "./lib/poker";
import NotFound from "./lib/notFound";

export function App() {
  return (
    <LocationProvider>
      <Router>
        <Landing path="/" />
        <Poker path="/session/:id" />
        <NotFound default />
      </Router>
    </LocationProvider>
  );
}
